### ISSUE TITLE
Not allowed to push new versions for this pod.

### ISSUE THREAD

**Issue by John-Lluch** [CocoaPods/cocoapods-trunk#23]
I am getting this when attempting to update MY pod file. 

[!] You are not allowed to push new versions for this pod.

Why?. What can I do or where can I look at?.

Thanks

**Comment by galkeidar** [comment]
Can pod have more than one owner?

**Comment by AliSoftware** [comment]
@galkeidar yes they can. One of the current owner of the pod on trunk can simply run `pod trunk add-owner` in their terminal to add a new owner to their pod so they're allowed to push on trunk too. Pretty common for pods developed by a team of people.

**Comment by Blackjacx** [comment]
Hey,

I just realised that one of my pod has been assigned to the email of my former employer. I now don't have access to this email but need to update my pod. I already send a dispute. Can somebody please transfer the ownership to me?

The pod is the "SHDateFormatter". You can simply verify that it is my pod since it is located in my Github account.

Thanks in advance,
Stefan

**Comment by orta** [comment]
@Blackjacx please don't re-open old posts, you already submitted a claim - your dispute didn't include your new email address, so I'm not sure what to add you to

**Comment by Blackjacx** [comment]
Oh sorry Orta. It is the same email address but with @gmail.com.

**Comment by orta** [comment]
Cool - done 👍
